

if(!require(plyr))
  install.packages("plyr")
if(!require(ggplot2))
  install.packages("ggplot2")
if(!require(wordcloud))
  install.packages("wordcloud")
if(!require(RColorBrewer))
  install.packages("RColorBrewer")
if(!require(tm))
  install.packages("tm")
if(!require(janeaustenr))
  install.packages("janeaustenr")
if(!require(dplyr))
  install.packages("dplyr")
if(!require(stringr))
  install.packages("stringr")
if(!require(stringi))
  install.packages("stringi")
if(!require(tidytext))
  install.packages("tidytext")
if(!require(reshape2))
  install.packages("reshape2")
if(!require(tidyr))
  install.packages("tidyr")
if(!require(igraph))
  install.packages("igraph")
if(!require(ggraph))
  install.packages("ggraph")
if(!require(topicmodels))
  install.packages("topicmodels")
if(!require(devtools))
  install.packages("devtools")



library(plyr)
library(ggplot2)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(janeaustenr)
library(dplyr)
library(stringr)
library(stringi)
library(tidytext)
library(reshape2)
library(tidyr)
library(igraph)
library(ggraph)
library(topicmodels)
library(devtools)

if(!require(widyr))
  install_github("dgrtwo/widyr")
library(widyr)
